sequenceDiagram
    actor VLDev as VL developer
    participant Git as Git repo<br>(.binder/)
    participant CI as CI (GH actions)
    participant Binder as BinderHub
    participant GHCR as OCI registry (ghcr.io)
    VLDev ->> Git: commit
    Git ->> CI: trigger virtual-lab-action

    alt if .binder/tests exists
        CI ->> CI: build and test image
        CI ->> VLDev: report status
    else else
        CI ->> VLDev: show “please test it yourself” and link to binder
        VLDev ->> Binder: /v2/gh/org/repo/my_branch
        Binder ->>+ Binder: trigger image build
        Binder ->> Git: clone my_branch
        Git ->> Binder: ...
        Binder -->>- GHCR: push image
        Binder ->> Binder: start VL
        Binder ->> VLDev: redirect
    end
